### ISSUE TITLE
Problems with variance_scaling_initializer

### ISSUE THREAD

**Issue by gargleblaster** [sebastianheinz/stockprediction#1]
I have run into two issues with line 59.

When run as shown, I get:

> AttributeError: module 'tensorflow' has no attribute 'variance_scaling_initializer'

If I change the line to read
`weight_initializer = tf.contrib.layers.variance_scaling_initializer(mode="fan_avg", distribution="uniform", scale=sigma)`
I then get this error:

> TypeError: variance_scaling_initializer() got an unexpected keyword argument 'distribution'

I only installed TensorFlow last week, and your file is only 23 days old, so I doubt that we have a version issue.  Do these errors mean anything to you?

**Comment by gargleblaster** [comment]
If I change the line to (note FAN_AVG is now in caps):
`weight_initializer = tf.contrib.layers.variance_scaling_initializer(mode="FAN_AVG")`

it will run, but the epoch graphs are empty.

**Comment by apovtx** [comment]
I just run it with tensorflow 1.4.1 (from pip --upgrade) and the original version seems to be working fine

**Comment by sebastianheinz** [comment]
Code is properly working with current TensorFlow version (1.4.1).
